<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>D2RCharViewer.Parsers</AssemblyName>
    <RootNamespace>D2RCharViewer.Parsers</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../D2RCharViewer.Core/D2RCharViewer.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Serilog" Version="4.0.0" />
  </ItemGroup>
</Project>